<?php

namespace Database\Seeders;

use App\Models\Enums\UserType;
use App\Models\OpeningHours;
use App\Models\Pharmacy;
use App\Models\User;
use Illuminate\Database\Seeder; // adapte selon ta config

class PharmacySeeder extends Seeder
{
    public function run()
    {
        $pharmaciesData = [

            [
                'groupe' => 'Groupe 1',
                'name' => 'Archange',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '79 20 01 83',
                'lat' => 12.3316752,
                'lng' => -1.5846717,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Avenir',
                'adresse' => '1200 Lgt, Av. BABANGUIDA face à la station Total',
                'phone' => '25 36 13 38',
                'lat' => 12.3754163,
                'lng' => -1.4939537,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Bang-poore',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 47 96 86',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Baowendsom',
                'adresse' => 'Tampouy sur le ouveau goudron du collège Notre Dame de l\'Espérance non loin de la "La Roche"',
                'phone' => '25 41 44 99',
                'lat' => 12.4038197,
                'lng' => -1.5775586,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Barkwendé',
                'adresse' => 'Arrdt 8, Sect 35, Face à la cité de Rimkièta',
                'phone' => '25 40 85 90',
                'lat' => 12.3742698,
                'lng' => -1.6084535,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Beatitudes',
                'adresse' => 'Blvd. France-Afrique Ouaga 2000 en face de la cité Azimo',
                'phone' => '25 37 47 11',
                'lat' => 12.30753,
                'lng' => -1.5283899,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Benaia',
                'adresse' => 'Katre-yaare ex secteur 29',
                'phone' => '25 37 28 30',
                'lat' => 12.3499844,
                'lng' => -1.4792868,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Bonheur',
                'adresse' => 'Bonheur Ville à 100 mètres de l\'Eglise du 75ème anniversaire',
                'phone' => '63 73 81 82',
                'lat' => 12.3139329,
                'lng' => -1.5551086,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Camille',
                'adresse' => 'Av. Charles De Gaules - Hôtel des finances de Dassasgho',
                'phone' => '25 36 61 27',
                'lat' => 12.3757877,
                'lng' => -1.4788303,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Centre',
                'adresse' => '460, Av de la nation collée à Telecel siège',
                'phone' => '25 31 16 60',
                'lat' => 12.3717460,
                'lng' => -1.5242617,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Crystal',
                'adresse' => 'Face à la nouvelle Mairie de l\'Arrdt 9; vers Centre Medical DON ORIONE, sect 38',
                'phone' => '60 46 08 08',
                'lat' => 12.4196966,
                'lng' => -1.5586378,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Des Apôtres',
                'adresse' => 'Arrdt 12, Sect 52 non loin de l\'Eglise catholique Notre Dame des Apôtres',
                'phone' => '25 38 03 82',
                'lat' => 12.327067,
                'lng' => -1.5125047,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Desa',
                'adresse' => 'Tanghin, non loin de Hôtel Ricardo',
                'phone' => '25 47 50 50',
                'lat' => 12.3916993,
                'lng' => -1.5243668,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Diaby',
                'adresse' => 'Face au Festival des Glaces à koulouba',
                'phone' => '25 33 50 00',
                'lat' => 12.3652843,
                'lng' => -1.5168797,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Dominique Kabore',
                'adresse' => '',
                'phone' => '25 38 48 84',
                'lat' => 12.3299577,
                'lng' => -1.5263706,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'El-wanoogo',
                'adresse' => 'A côté du Marché de Wayalghin, non loin de la Clinique de l\'Est',
                'phone' => '25 40 70 22',
                'lat' => 12.3986684,
                'lng' => -1.4635623,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Elite',
                'adresse' => 'Avenue Yennega route de Yagma',
                'phone' => '25 41 91 77',
                'lat' => 12.3965179,
                'lng' => -1.609766,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'GUUDMA',
                'adresse' => '',
                'phone' => '70 28 48 60',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Hosanna',
                'adresse' => 'Route de fada, Nioko 1, Saaba en allant vers la Consolatrice',
                'phone' => '25 41 26 48',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Jober',
                'adresse' => 'IMMEUBLE SIMPORE AVENUE DIEUDONNE',
                'phone' => '25 45 51 75',
                'lat' => 12.3241372,
                'lng' => -1.5561819,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Katra (ex Silmissin)',
                'adresse' => 'Située à Kalgondé après la gare RAHIMO',
                'phone' => '25 36 61 27',
                'lat' => 12.3472070,
                'lng' => -1.5030372,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Keneya',
                'adresse' => 'Avenue Oumarou KANAZOE porte 734 côté ouest mur lycée Municipal BAMBATA',
                'phone' => '25 30 71 38',
                'lat' => 12.3582695,
                'lng' => -1.5329146,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Kossodo',
                'adresse' => 'En face de l\'abattoir de Kossodo, après la BOA',
                'phone' => '25 35 63 04',
                'lat' => 12.4172523,
                'lng' => -1.4733789,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Lanibougna',
                'adresse' => 'Tanghin, quartier Nonghin, non loin de la Station Radar',
                'phone' => '25 48 07 97',
                'lat' => 12.4160359,
                'lng' => -1.5239259,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Lanzané',
                'adresse' => 'En face de l\'Auto-Ecole Magnificat à la Zone Une (1)',
                'phone' => '25 47 10 65',
                'lat' => 12.3629432,
                'lng' => -1.4645464,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Lendimi',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '63 81 59 18',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Les Champions',
                'adresse' => 'A environ 100 mètres du marché de 14 Yaar',
                'phone' => '51 00 15 25',
                'lat' => 12.3797706,
                'lng' => -1.4605703,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Liberté',
                'adresse' => '60m de la station SHELL de la cité an III, en direction du marché Sankar-yaare',
                'phone' => '25 30 74 52',
                'lat' => 12.3777896,
                'lng' => -1.5318734,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Lina',
                'adresse' => 'Avenue Kwamé N\'Krumah non loin du Paradis des Meilleurs Vins',
                'phone' => '73 48 35 65',
                'lat' => 12.3553917,
                'lng' => -1.5167413,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Magnificat',
                'adresse' => 'Sect 50 Karpala, 1km après rue Sankara Inoussa, 300m du dernier six-mètre à gauche',
                'phone' => '25 39 63 38',
                'lat' => 12.3289477,
                'lng' => -1.4764567,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Maré',
                'adresse' => 'Gounghin, non loin du Stade du 4 Août',
                'phone' => '25 34 11 28',
                'lat' => 12.3631535,
                'lng' => -1.5498608,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Minitché',
                'adresse' => 'BelleVille non Loin du rond-point de la transition',
                'phone' => '72 25 76 76',
                'lat' => 12.2896266,
                'lng' => -1.5739689,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Monderou',
                'adresse' => 'Quartier Nonsin-face station OTAM rue karamogo non loin du CSPS de Nonsin',
                'phone' => '25 34 05 28',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Nanle',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 47 70 80',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Neerwaya',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '63 93 73 73',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Nouvelle',
                'adresse' => 'Non loin de la station Petrofa Cissin au croisemen de la circulaire et de la route bnheur ville',
                'phone' => '25 30 61 33',
                'lat' => 12.3671395,
                'lng' => -1.5194434,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Pelega',
                'adresse' => 'Arrdt N°3, Av du Yatenga à 100m du rond-point de la jeunesse (près du ciné de Tampouy)',
                'phone' => '25 35 05 01',
                'lat' => 12.3887476,
                'lng' => -1.5705151,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Rayib-Tiga',
                'adresse' => 'Av. Jean-Baptiste OUEDRAOGO 800m coté Nord de la Clinique Note-Dame-de-la-Paix SOMGAMDE',
                'phone' => '65 32 11 53',
                'lat' => 12.4053719,
                'lng' => -1.5063124,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Rivage',
                'adresse' => 'Av. du Kadiogo, 200m à l\'Est de l\'échangeur de l\'Ouest, en face de l\'agence ECOBANK de Gounghin',
                'phone' => '25 34 19 39',
                'lat' => 12.3541493,
                'lng' => -1.5524141,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Saint Bernard',
                'adresse' => 'Face à la trame d\'acceuil Ouaga 2000(Av. Ousmane SEMBENE)',
                'phone' => '25 45 14 82',
                'lat' => 12.3122831,
                'lng' => -1.4888735,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Saint François D\'Assise',
                'adresse' => 'Zone du bois non loin de l\'agence ONATEL',
                'phone' => '25 36 85 85',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Saint Jean',
                'adresse' => 'Rue 30.240 Blwd. Tansoaba; Bâtiment de ISDA, 500m de l\'Hôpital de Bogodgo Ex-CMA 30',
                'phone' => '25 37 00 33',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Siloé',
                'adresse' => 'Samandin ex Sect 07 Av. Bassawarga (FaceChâteau Mogho Naaba)',
                'phone' => '25 31 50 68',
                'lat' => 12.3559773,
                'lng' => -1.5273022,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Song Taaba',
                'adresse' => '100m de la SONABEL Bendogo, Cité de l\'avenir',
                'phone' => '25 36 64 62',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Talè',
                'adresse' => 'Route de Bobo, entre les stations Total et Shell et le lycée Bethesda',
                'phone' => '71 62 08 08',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Tenedia',
                'adresse' => 'Kamboinsin en face de 2IE',
                'phone' => '63 93 00 19',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Tengandogo',
                'adresse' => '100m après le trounant du CHU Tengandogo à droite avant la station TOTAL',
                'phone' => '01 10 33 82',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Trypano',
                'adresse' => 'Derrière le Centre de Transfusion Sanguine (CNTS) Ouaga non loi de la Trypanon (Paspanga près de la station OTAM)',
                'phone' => '25 33 29 41',
                'lat' => 12.3807982,
                'lng' => -1.5102194,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Wend La Laafi',
                'adresse' => 'Ouartie Pissy, Route de Bobo, en face de la station Shell de Pissy',
                'phone' => '25 43 12 13',
                'lat' => 12.3422587,
                'lng' => -1.572761,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Wend Lamita',
                'adresse' => 'Sect N°8 avenue du Yatenga Face école Kologh-Naba',
                'phone' => '25 34 15 87',
                'lat' => 12.380624,
                'lng' => -1.5499241,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 1',
                'name' => 'Yathrib',
                'adresse' => '200m du marché de Saaba',
                'phone' => '70 24 97 63',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],

            // Groupe 2
            [
                'groupe' => 'Groupe 2',
                'name' => 'Adadoua',
                'adresse' => 'Entre le CMA de Pissy et le Centre Médical Source de Vie (A 200m du CM source de vie)',
                'phone' => '63 88 39 39',
                'lat' => 12.3337843,
                'lng' => -1.5620317,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Aéroport',
                'adresse' => 'Face à l\'ASECNA à 500m de l\'Aéroport International de Ouagadougou',
                'phone' => '25 31 42 22',
                'lat' => 12.3504685,
                'lng' => -1.5213054,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Agora-Rood Wooko',
                'adresse' => 'Marché Rood Wooko face à DIACFA Librairie',
                'phone' => '57 84 47 49',
                'lat' => 12.3710898,
                'lng' => -1.5211561,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Amaro',
                'adresse' => 'Av du Kadiogo Gounghin Petit Paris entre le service passeport et le pont kadiogo',
                'phone' => '25 34 33 28',
                'lat' => 12.3612337,
                'lng' => -1.5398309,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Amina',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 36 76 65',
                'lat' => 12.3696055,
                'lng' => -1.4840283,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Ar-rahma',
                'adresse' => 'Av Yatenga à Tampouy, face à la Caisse Populaire',
                'phone' => '25 35 09 86',
                'lat' => 12.3895173,
                'lng' => -1.5738866,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Augustine',
                'adresse' => 'Situé à Ouaga 200 à environ 300m de l\'échangeur en partance vers le monument des martyres',
                'phone' => '25 37 61 00',
                'lat' => 12.325577,
                'lng' => -1.5030942,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Bao Neere',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 45 88 88',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Boulmiougou',
                'adresse' => 'Arrdts n°6, Sect 27, 166 rue de Boassa, Pissy à 200m du Complexe Scolaire Sainte-Famille',
                'phone' => '25 43 12 68',
                'lat' => 12.3349939,
                'lng' => -1.5795391,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Cathédrale',
                'adresse' => '38 Av de la cathédrale , Côté Ouest de la cathédrale, face à la station TOTAL',
                'phone' => '25 31 28 07',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Cité An 3',
                'adresse' => 'Larlé en face de la maternité Pogbi(Centre Médical Urbain)',
                'phone' => '25 33 19 66',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Danouma',
                'adresse' => 'Bonheur Ville à 300mètres du rond-point de la transition',
                'phone' => '25 39 55 54',
                'lat' => 12.2829766,
                'lng' => -1.5638728,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Dapoya',
                'adresse' => 'Dapoya, face immeuble acimex, Sankar-Yaaré',
                'phone' => '25 31 32 01',
                'lat' => 12.3802564,
                'lng' => -1.5238771,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Delwindé',
                'adresse' => 'Sect 42 de l\'Arrdt 10, à 700m de l\'échangeur de l\'EST(Kossodo) RN3',
                'phone' => '25 36 72 80',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Denisa',
                'adresse' => 'Secteur 14 Komsilga non loin du CHU de Tengandogo',
                'phone' => '71 82 76 60',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Faso',
                'adresse' => 'Blvd France - Afrique à 300m de l\'agence BOA à france-Afrique, Patte-d\'oie',
                'phone' => '25 38 19 29',
                'lat' => 12.3222074,
                'lng' => -1.5280613,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Flayiri',
                'adresse' => 'ZAD Face à la Station PETROFA',
                'phone' => '25 40 73 44',
                'lat' => 12.3370658,
                'lng' => -1.5080412,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Hamdalaye',
                'adresse' => 'Quartier Hamdalaye (sect 8), Près du marché du 10 Yaar',
                'phone' => '25 34 36 94',
                'lat' => 12.3752816,
                'lng' => -1.5513663,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Hanniel',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 36 60 20',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Hope',
                'adresse' => 'Route de Fada en face du lycée Naba Yemdé',
                'phone' => '71 14 22 22',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Horizon',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '73 17 06 06',
                'lat' => 12.3093603,
                'lng' => -1.539118,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Jabnéel',
                'adresse' => 'Route Coté Sud SONABEL Bendego à 700m',
                'phone' => '25 36 66 01',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'jireh',
                'adresse' => 'a côté de l\'école primaire Naaba yandfo à Pissy',
                'phone' => '25652139',
                'lat' => 12.3269397,
                'lng' => -1.5648128,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Joriel',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 48 98 98',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Jourdain',
                'adresse' => 'Blvd Tansoba, 100m de l\'hôpital Pédiatrique',
                'phone' => '25 36 06 86',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Karpala',
                'adresse' => 'Route CFAO-KARPALA(Hopital ex-Sect 30)',
                'phone' => '25 37 14 14',
                'lat' => 12.3321873,
                'lng' => -1.4926434,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Ko-Viiga',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 66 33 33',
                'lat' => 12.3841609,
                'lng' => -1.607957,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Koulouba',
                'adresse' => 'Koulouba à 200m côté Ouest du marché de Boins-Yaaré',
                'phone' => '25 31 19 18',
                'lat' => 12.3666291,
                'lng' => -1.5096143,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Koumajer',
                'adresse' => 'Non loin du Palais de Justice Karpala',
                'phone' => '25 40 20 20',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Les Lauriers',
                'adresse' => 'Karpala sur la voie des Pylônes non loin de la Cave Simporé',
                'phone' => '25 48 37 55',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Marlass',
                'adresse' => 'Tanghin sect 17, après Arbr Yaar en face de la boulangerie Fatim',
                'phone' => '78 55 00 52',
                'lat' => 12.4060725,
                'lng' => -1.5403505,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Martin',
                'adresse' => 'Av. de la Dignité, non loin de la radio SAVANE FM',
                'phone' => '25 50 84 59',
                'lat' => 12.3281731,
                'lng' => -1.5510688,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Meira',
                'adresse' => 'Nioko 2 non loin du marché, route de Ziniaré, à 500m de la Station Total',
                'phone' => '25 65 12 46',
                'lat' => 12.4257167,
                'lng' => -1.46304,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Meteba',
                'adresse' => 'Ex sect 23 quartier Tanghin 365 rue JEAN-PAUL II',
                'phone' => '25 33 53 33',
                'lat' => 12.3945076,
                'lng' => -1.5154099,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Mitspah',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 45 85 85',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Nayyira',
                'adresse' => 'Katre Yaar après la gare de Taxis',
                'phone' => '63 78 44 44',
                'lat' => 12.3473174,
                'lng' => -1.4738417,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Neima',
                'adresse' => 'Toukin Yaar, quartier Somgandé',
                'phone' => '25 65 56 82',
                'lat' => 12.4119504,
                'lng' => -1.4960004,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Nemadis',
                'adresse' => 'Rue Bogodogo à 500m du Rond point SANDOF en direction de SOGELB(vers le SIAO)',
                'phone' => '25 48 09 66',
                'lat' => 12.3564914,
                'lng' => -1.4911107,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Prim\'Sante',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '77 55 78 12',
                'lat' => 12.3421098,
                'lng' => -1.5527741,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Progrés',
                'adresse' => 'Pissy, route de Bobo face à UBIPHARM',
                'phone' => '25 43 01 62',
                'lat' => 12.3436992,
                'lng' => -1.5689194,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Rakismanegré',
                'adresse' => 'Non loin du Chateau d\'eau de Tampouy, sur la voie de la nouvelle mairie de l\'arrdt 9',
                'phone' => '62 50 58 18',
                'lat' => 12.4182956,
                'lng' => -1.5687944,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Saint Joseph',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 46 55 08',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Sainte Véronique',
                'adresse' => 'En face du marché de Zagtouli sur la route CIMAT',
                'phone' => '63 26 04 04',
                'lat' => 12.3279934,
                'lng' => -1.6325527,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Samandin',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '03 38 57 57',
                'lat' => 12.3556092,
                'lng' => -1.5340657,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Sangoulé Lamizana',
                'adresse' => 'Av. Yennega à côté de Marina Market centre Ville',
                'phone' => '25 41 13 00',
                'lat' => 12.3651894,
                'lng' => -1.5209219,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Schiffey',
                'adresse' => 'Non loin du Blvd de la jeunesse vers le foyer des Sapeurs Pompiers du Camp Sangoulé Lamizana',
                'phone' => '25 40 27 42',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Sig-Noghin',
                'adresse' => 'Av. Naaba Ziiwendé 150m du rond point de Rimkièta',
                'phone' => '25 35 09 77',
                'lat' => 12.3903118,
                'lng' => -1.5993509,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Sigri',
                'adresse' => '2828 Av. du Conseil de l\'Entente Gounghin, non loin de la Station Total et Marina Market',
                'phone' => '25 41 21 48',
                'lat' => 12.3585045,
                'lng' => -1.5488971,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Somketa',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 65 82 73',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Sud',
                'adresse' => 'Centre Commerciale Ouaga 2000 à coté de l\'Hôtel Libya',
                'phone' => '25 38 42 82',
                'lat' => 12.3065734,
                'lng' => -1.5267587,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Talba',
                'adresse' => 'Av. Charles De Gaulle, face au Scolosticat, Zogona',
                'phone' => '25 36 22 25',
                'lat' => 12.3764288,
                'lng' => -1.4909940,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Tanko',
                'adresse' => 'Face au CMA Paul VI sur la route de Kamboinsé',
                'phone' => '25 35 15 57',
                'lat' => 12.3994142,
                'lng' => -1.5555928,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Ti-Bangre',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 45 45 95',
                'lat' => 12.339786,
                'lng' => -1.5859983,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Univers',
                'adresse' => 'Voie principale Saaba, à 500m de la prefecture de Saaba',
                'phone' => '25 41 99 65',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Viim',
                'adresse' => '100 mètres du Centre Médical de Nagrin',
                'phone' => '01 92 88 88',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Vincent de Paul',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '01 92 88 88',
                'lat' => 12.3594654,
                'lng' => -1.4737954,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Wati',
                'adresse' => 'Cissin à 200m de l\'Ecole de Santé St Edvige',
                'phone' => '25 38 52 92',
                'lat' => 12.3443619,
                'lng' => -1.5404714,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Yobi',
                'adresse' => 'A 200m de la Gendarmerie de Paspanga',
                'phone' => '25 31 16 30',
                'lat' => 12.3782928,
                'lng' => -1.5118671,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 2',
                'name' => 'Zidou',
                'adresse' => 'Balkuy, en face de l\'immeuble Yelhi',
                'phone' => '61 07 88 60',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],

            // Groupe 3
            [
                'groupe' => 'Groupe 3',
                'name' => 'Aïmèvo',
                'adresse' => 'En Face de la Mairie de Karpala(Arrdt. 11) env. 20m après le Chateau de l\'ONEA',
                'phone' => '25 39 36 99',
                'lat' => 12.3390042,
                'lng' => -1.4798680,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Arzouma',
                'adresse' => 'Quartier Pissy, à 100m de la clinique du Plateau, non loin de la salle de ciné de Pissy',
                'phone' => '25 48 01 53',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Avé Maria',
                'adresse' => 'Karpala non loin de la Station Oryx et eau OCEAN',
                'phone' => '25 47 98 88',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Balkuy',
                'adresse' => 'Route de Pô, non loin du rond-point des Droits Humains',
                'phone' => '25 37 51 36',
                'lat' => 12.3095647,
                'lng' => -1.4822765,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Baraka',
                'adresse' => 'Côté Est de la Cours du Ouidi Naaba',
                'phone' => '25 33 02 72',
                'lat' => 12.3735531,
                'lng' => -1.5389704,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Belle Ville',
                'adresse' => 'Route de Komsilga/ BRAFASO/ 75e Anniversaire AD',
                'phone' => '25 40 84 14',
                'lat' => 12.307727,
                'lng' => -1.557804,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Blessing',
                'adresse' => '',
                'phone' => '01 75 99 75',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Carrefour',
                'adresse' => 'Av. Kadiogo En face du rond point du 02 Octobre et du Lycée Marien Gouabi',
                'phone' => '25 33 23 10',
                'lat' => 12.3686454,
                'lng' => -1.5312362,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Charis',
                'adresse' => 'Cite relai de Agtouli, route de bobo après le complexe scolaire Saint Justin',
                'phone' => '25 43 90 91',
                'lat' => 12.3296215,
                'lng' => -1.6151104,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Christvi',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 48 59 59',
                'lat' => 12.3921028,
                'lng' => -1.5336767,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Concorde',
                'adresse' => 'Av. Kwame N\'Krumah non loin de Zabre Daaga',
                'phone' => '25 31 29 49',
                'lat' => 12.3662736,
                'lng' => -1.5189930,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Coura',
                'adresse' => '200m Côté oueste du rond-point des Droits Humains',
                'phone' => '25 38 83 90',
                'lat' => 12.327362,
                'lng' => -1.5193038,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Djabal (ex Mariama)',
                'adresse' => 'Kamsonghin secter 64, Av Ouezzin Coulibaly(entre la zone Zaca et le château de Mogho Naba)',
                'phone' => '25 30 05 76',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Djimbia',
                'adresse' => '400m après le drond-point du Rotary, Tanghin',
                'phone' => '78 83 62 74',
                'lat' => 12.4016380,
                'lng' => -1.5143299,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Dunia',
                'adresse' => 'Avenue des Arts/ Face au rond-point des Artiste ex sect. 14, 1200Logts',
                'phone' => '25 36 20 51',
                'lat' => 12.3592658,
                'lng' => -1.4952633,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Ecoles',
                'adresse' => 'Rue des écoles à Paspanga',
                'phone' => '25 31 52 32',
                'lat' => 12.3612288,
                'lng' => -1.5399014,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Fabere',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 41 05 75',
                'lat' => 12.4127586,
                'lng' => -1.5708048,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Galiam',
                'adresse' => 'Tampouy, route de la mairie de Sig-Nonghin, non loin du rond-point de la cité AZIMO',
                'phone' => '25 65 31 65',
                'lat' => 12.3963457,
                'lng' => -1.5620113,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Georgette',
                'adresse' => 'Bassinko, Route de Ouahigouya, à coté de la boulangerie Baraka',
                'phone' => '25 50 05 28',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Hamamickely',
                'adresse' => 'Quartier Somgandé à 300m du CSPS du Sect. 19\'ex sect 25) Arrdt 4',
                'phone' => '73 78 32 99',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Indépendance',
                'adresse' => '370 Avenue Eli SARE, à 500 mètres de EAU Sahel Ouaga 2000',
                'phone' => '25 37 68 71',
                'lat' => 12.3704636,
                'lng' => -1.5161272,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Jeunesse',
                'adresse' => 'Blvd de la Jeunesse, Hamdalaye à 200m de lhippodrome',
                'phone' => '25 34 35 04',
                'lat' => 12.3719156,
                'lng' => -1.5578295,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Kamboinsin',
                'adresse' => 'Face du Centre Emetteur de KAMBOINSIN',
                'phone' => '62 57 49 49',
                'lat' => 12.4339155,
                'lng' => -1.5494816,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Kamin',
                'adresse' => 'Sect. 06 Gounghin, côté Est du marché de Goughin',
                'phone' => '25 34 30 28',
                'lat' => 12.3576168,
                'lng' => -1.5456681,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Kilwin',
                'adresse' => 'Route de Ouahigouya, Côté station Shell, Face à Tecin Yaar, Tampouy',
                'phone' => '25 50 84 62',
                'lat' => 12.3903226,
                'lng' => -1.5804844,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'La Famille',
                'adresse' => 'Quartier Pissy, Sect. 12 Arrdt 3, à 500m de Chic Hotel',
                'phone' => '25 43 06 85',
                'lat' => 12.3461490,
                'lng' => -1.5829894,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'La Sainte Trinité',
                'adresse' => 'Wemtenga à coté de la Caisse Populaire Song-Taaba de Dagnoen',
                'phone' => '25 41 26 46',
                'lat' => 12.3686294,
                'lng' => -1.4884359,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Naab Raga',
                'adresse' => 'Samandin, Avenue Oumarou KANAZOE à 100m du marché de Naab Raage',
                'phone' => '70 14 39 77',
                'lat' => 12.3529507,
                'lng' => -1.5315691,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Naaba-koom',
                'adresse' => '200m de la Clinique Note-Dame-de-la-Paix',
                'phone' => '25 48 33 34',
                'lat' => 12.3992447,
                'lng' => -1.5033346,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Nagrin',
                'adresse' => 'Route de Saponé avant l\'hôpital Balise Compaoré',
                'phone' => '25 46 90 48',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Nazani',
                'adresse' => 'xx',
                'phone' => '25 36 65 10',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Ninrwa',
                'adresse' => 'Toute Benogo - Kossodo( Av Colonel A. Michel OUEDRAOGO) Bogodogo à 400m du marché',
                'phone' => '25 41 80 38',
                'lat' => 12.4051573,
                'lng' => -1.4565872,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Noom-Wendé',
                'adresse' => 'Rue Liwaga, après le lycée UNIVERSALIS en allant à Pissy',
                'phone' => '01 25 17 17',
                'lat' => 12.3187974,
                'lng' => -1.538019,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Pierre Tapsoba',
                'adresse' => 'Saaba à 100m de la Station OTAM',
                'phone' => '25 50 81 48',
                'lat' => 12.3976775,
                'lng' => -1.4433463,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Pharmacie Poste',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 31 84 24',
                'lat' => 12.3692227,
                'lng' => -1.5228390,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Pissy',
                'adresse' => 'Côté Est CMA de Pissy',
                'phone' => '25 43 13 35',
                'lat' => 12.3373385,
                'lng' => -1.5643054,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Renaissance',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '68 91 10 10',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Saaba',
                'adresse' => 'En face du lycée Notre Dame des Victoires',
                'phone' => '25 40 86 99',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Sacré Cœur',
                'adresse' => 'Avenue Simon Compaoré, à 500m du lycée Miste de Gounghin, en partant vers Watam Kaiser',
                'phone' => '25 34 60 60',
                'lat' => 12.3514654,
                'lng' => -1.5462785,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Saint Julien',
                'adresse' => 'A 100m du rond-point de la Patte-d\'oie, sur l\'avenue Bassawarga',
                'phone' => '25 38 06 10',
                'lat' => 12.3349383,
                'lng' => -1.5261773,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Saint Lazare',
                'adresse' => '1200 Logts, à coté du Pont(du Canal) de Bons Yaare',
                'phone' => '25 36 86 48',
                'lat' => 12.3791200,
                'lng' => -1.5283652,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Saint Michel',
                'adresse' => 'Rimkièta non loin de la pharmacie Barkwendé',
                'phone' => '25 45 48 08',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Santé-Vitalité',
                'adresse' => 'Rue WARABA, 500m après la cité de l\'ASECNA en quittant le boulevard France-Afrique',
                'phone' => '25 40 94 13',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Savane',
                'adresse' => 'A 500m de l\'école des Douanes coté Nord',
                'phone' => '70 85 01 61',
                'lat' => 12.3777192,
                'lng' => -1.5210675,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Seneve',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '60 12 12 73',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Taoko',
                'adresse' => 'Blvd Tansoba, à 500m de l\'échangeur de l\'Est',
                'phone' => '25 36 69 27',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Téranga',
                'adresse' => '13 avenue Babanguida, Zogona',
                'phone' => '25 36 09 70',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Ti-yéélé',
                'adresse' => 'Rue 28.284, secteur 43 non loin du lycée Ste Collette',
                'phone' => '64 36 46 36',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Wayalghin',
                'adresse' => 'En Face du mur du camps CRS, vers ANTBA(en venant de la MACO à gauche après l\'ENAREF)',
                'phone' => '25 39 52 08',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Wend-denda',
                'adresse' => 'Sect. 9, quartier Ouidi, Avenue Yatenga, entre la station Total de Larlé et ECOBANK Ouidi',
                'phone' => '71 50 94 92',
                'lat' => 12.3772185,
                'lng' => -1.5440600,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Yempabou',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 39 40 61',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Yennenga',
                'adresse' => 'Blvd Tansoba face à la mairie de BOGODOGO',
                'phone' => '25 37 03 37',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Zone I',
                'adresse' => 'A 200m du marché de la Zone 1',
                'phone' => '25 48 15 13',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 3',
                'name' => 'Zoungrana',
                'adresse' => 'Sect. 17 Tanghin rue 23/125 à coté de la boulangerie Wend Konta',
                'phone' => '25 40 98 75',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],

            // Groupe 4
            [
                'groupe' => 'Groupe 4',
                'name' => '1200 Logements',
                'adresse' => 'Av. Babanguida face à l\'Hopital Saint CAMILLE',
                'phone' => '25 36 02 52',
                'lat' => 12.3669978,
                'lng' => -1.4940283,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Adama',
                'adresse' => 'En face du Marché de Pissy non loin de la Caisse Populaire',
                'phone' => '62 33 77 77',
                'lat' => 12.3357995,
                'lng' => -1.5682597,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Afiya',
                'adresse' => 'Zone 1 à 300m du lycée Badenya, Face au non loti',
                'phone' => '66 11 73 65',
                'lat' => 12.3554267,
                'lng' => -1.4686317,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Amitié Miyougou',
                'adresse' => 'Boulevard de la circulation, sect 25 Cissin à 200m du marché de Paagla yiri',
                'phone' => '25 38 52 36',
                'lat' => 12.3345884,
                'lng' => -1.5352294,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Angèle',
                'adresse' => 'Tampouy coté Sud du Centre Médical Paul VI, face au monument des Martyrs.',
                'phone' => '25 35 07 17',
                'lat' => 12.3900232,
                'lng' => -1.5629526,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Bassinko',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 41 71 50',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Bedjou',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 47 58 25',
                'lat' => 12.3443293,
                'lng' => -1.4799548,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Bethania',
                'adresse' => 'Av. Oumarou KANAZOE coté Est CBC',
                'phone' => '25 31 31 41',
                'lat' => 12.3641505,
                'lng' => -1.5336678,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Choukroullah',
                'adresse' => '300m du Centre Médicale de Nagrin',
                'phone' => '25 40 93 76',
                'lat' => 12.286599,
                'lng' => -1.5381734,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Circulaire Sède',
                'adresse' => 'ex Sect 15, face à la Station TOTAL Ouaga-inter',
                'phone' => '25 47 61 27',
                'lat' => 12.3325457,
                'lng' => -1.5162308,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'De l\'Alliance',
                'adresse' => 'Rimkièta à 50mètres du Lycée Général Kadiogo III',
                'phone' => '66 06 35 39',
                'lat' => 12.3852251,
                'lng' => -1.6028525,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'De Hippodrome',
                'adresse' => '116 boulevard Tensoba Bugum, côté Est de l\'hippodrome de Nonsin',
                'phone' => '25 34 02 32',
                'lat' => 12.3756732,
                'lng' => -1.5575485,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Diawara',
                'adresse' => 'Rue du grand marché - Centre ville coté LONAB',
                'phone' => '25 30 61 68',
                'lat' => 12.3188496,
                'lng' => -1.5326651,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'El Shaddai',
                'adresse' => 'Benogo à 100 mètres du Pont Ana na yélé',
                'phone' => '25 41 00 02',
                'lat' => 12.4145175,
                'lng' => -1.4634325,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Espoir',
                'adresse' => 'Larlé face à la Maison des Jeunes',
                'phone' => '25 31 54 12',
                'lat' => 12.3727821,
                'lng' => -1.5458486,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Fraternité',
                'adresse' => '100m de ENAREF, Coté ECOBANK',
                'phone' => '25 36 48 00',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Gare',
                'adresse' => '103 rue des Douanes coté Nord UBA Siège',
                'phone' => '25 31 62 06',
                'lat' => 12.3747409,
                'lng' => -1.5215561,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Gemme',
                'adresse' => 'Cité AZIMMO Tampouy en face du lycée Privé Pang Ya Wendé',
                'phone' => '62 70 50 50',
                'lat' => 12.4053229,
                'lng' => -1.5599851,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Hambila',
                'adresse' => '',
                'phone' => '02 53 57 57',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Hamid',
                'adresse' => 'Route Nationale N°1 (RN1) e face de la SONAPOST de Zagtouly',
                'phone' => '79 61 31 72',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Hanahim',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 39 54 38',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Hôpital',
                'adresse' => 'A coté de l\'Hopital Yalgado Ouedraogo',
                'phone' => '25 30 66 41',
                'lat' => 12.3821996,
                'lng' => -1.5065921,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Iris',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 46 99 25',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Jean Paul II',
                'adresse' => 'Tanghin face à Arb-Yaar sect 17',
                'phone' => '25 41 81 54',
                'lat' => 12.4004904,
                'lng' => -1.5376327,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Kadiogo',
                'adresse' => '1207, Avenue Kwamé N\'Krumah, immeuble CNSS; Face à Coris Bank siège',
                'phone' => '25 31 87 88',
                'lat' => 12.3607101,
                'lng' => -1.5175128,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Kawsar',
                'adresse' => 'Karpala à 600m de la division fiscale(impôts)',
                'phone' => '73 20 77 87',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Kouma',
                'adresse' => 'Boulevard France-Afrique Ouaga 2000, à 100m de Ouaga FM',
                'phone' => '25 38 57 42',
                'lat' => 12.3065734,
                'lng' => -1.5267587,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'La Croix',
                'adresse' => 'Gounghin, Près de l\'échangeur de l\'ouest face au Jardin le Challege',
                'phone' => '25 34 12 64',
                'lat' => 12.3522908,
                'lng' => -1.5563301,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'La Roche',
                'adresse' => 'TAMPOUY, (Arrdt 3, sect. 15) en face du groupe scolaire NAA-TOUGOULE, Ex Nakeb-Zanga',
                'phone' => '25 39 51 32',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Lallé',
                'adresse' => 'Av Pierre Claver BADEMBIE NIEZIEN, 50m du feu tricolore, Kouritenga',
                'phone' => '79 07 06 22',
                'lat' => 12.3227051,
                'lng' => -1.5520794,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Le Rocher',
                'adresse' => 'Rue séparant Ouaga 2000 et PAtte d\'oie à 1km de la Mosquée KANAZOE',
                'phone' => '25 40 83 87',
                'lat' => 12.3176492,
                'lng' => -1.5178971,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'LesGrâces',
                'adresse' => 'Av. de la Concorde Nationale, secteur 17 Tanghin',
                'phone' => '60 80 80 77',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Loius Pasteur',
                'adresse' => 'Av. Dapoya à 400m de l\'église Catholique',
                'phone' => '25 33 58 67',
                'lat' => 12.3877235,
                'lng' => -1.4784072,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Maignon',
                'adresse' => 'Av. Bassawarga Kamsonghin face au CM de Samandin',
                'phone' => '78 83 61 36',
                'lat' => 12.3504047,
                'lng' => -1.5265294,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Miséricorde',
                'adresse' => 'Dassasgho, coté Nord de l\'Eglise de Karambiri à 300 mètres',
                'phone' => '25 65 22 64',
                'lat' => 12.3867301,
                'lng' => -1.4633678,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Musée',
                'adresse' => 'Blvd Tansoba côté Est du Mur du Musée National',
                'phone' => '25 36 68 41',
                'lat' => 12.3798926,
                'lng' => -1.4691832,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Natilgé',
                'adresse' => 'Blvd Tansoaba Waonre, en face du feu tricolore de l\'IDS',
                'phone' => '25 37 28 00',
                'lat' => 12.3585129,
                'lng' => -1.4833119,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Nioko I',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '61 97 70 48',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Nongui',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 40 84 88',
                'lat' => 12.384624,
                'lng' => -1.5752453,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Ouédraogo Remi',
                'adresse' => 'Av. des Tansoba KIEMA, sous l\'immeuble résidence Alice face à la SONABEL Zad',
                'phone' => '25 37 16 52',
                'lat' => 12.3351005,
                'lng' => -1.4990333,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Pingdba',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '78 37 93 81',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Principale',
                'adresse' => 'Av. Pascal ZAGRE Ouaga 2000 , Coté feux tricolores Présidence du faso, non loin de TV BF1',
                'phone' => '25 37 54 15',
                'lat' => 12.3061395,
                'lng' => -1.5039114,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Providence',
                'adresse' => 'Larlé, à 200m de la Gare STAF',
                'phone' => '25 31 86 48',
                'lat' => 12.3740726,
                'lng' => -1.5395562,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Rima',
                'adresse' => '',
                'phone' => '50 61 07 07',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Rimkieta',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '71 50 94 36',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Sahel',
                'adresse' => 'Av. du Président Sangoulé LAMIZANA. Koulaba sur alignement du siège de ORANGE',
                'phone' => '25 31 81 95',
                'lat' => 12.3662949,
                'lng' => -1.5146408,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Sainte Odile',
                'adresse' => 'Côté Est de la Cave Simporé à Karpala en allant vers Rayongo',
                'phone' => '51 69 77 77',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Sira',
                'adresse' => 'Route de Bobo, 100m de la Mairie de Boulmiougou',
                'phone' => '25 43 17 78',
                'lat' => 12.3416432,
                'lng' => -1.5808747,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Somgandé',
                'adresse' => 'Cité SOCOGIB Somgandé à 200m de la Boulangerie Wend Konta',
                'phone' => '70 14 39 25',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Sotisse',
                'adresse' => 'Quartier Wayalguin à coté de la Clinique de l\'Est',
                'phone' => '25 36 41 48',
                'lat' => 12.3973078,
                'lng' => -1.4687152,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Unité',
                'adresse' => 'Gounghin, Près de l\'échangeur de l\'ouest face au Jardn de la Challenge',
                'phone' => '25 40 27 57',
                'lat' => 12.3522908,
                'lng' => -1.5563301,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Vénégré',
                'adresse' => 'Arrdt 6 non loin de la Clinique EL Fateh Suka',
                'phone' => '25 43 09 87',
                'lat' => 12.3350482,
                'lng' => -1.5581465,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Vidal Bafa',
                'adresse' => 'Avenue Oumarou Kanazoé, Sect 7, Près de l\'école de l\'Onatel',
                'phone' => '25 31 52 88',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Vièl',
                'adresse' => 'Route de Kamboincé, Porte des soeurs après CMA PAUL VI',
                'phone' => '25 45 98 25',
                'lat' => 12.4245505,
                'lng' => -1.5510588,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Wend Kuuni',
                'adresse' => 'Blvd Charles De Gaulle non loin de la mosquée de l\'AEEMB',
                'phone' => '25 36 20 15',
                'lat' => 12.3756553,
                'lng' => -1.4875244,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Wend Yam',
                'adresse' => 'Route de Ouahigouya, à la fin des deux voies, 500m du marché de bétail',
                'phone' => '25 48 30 47',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Wend Zinkre',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 46 54 24',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Yan-marou',
                'adresse' => 'Pas d\'adresse disponible',
                'phone' => '25 46 50 06',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
            [
                'groupe' => 'Groupe 4',
                'name' => 'Yentema',
                'adresse' => 'En face du Marché de M\'ba Simon TOEGA, quartier Nagrin',
                'phone' => '56 56 00 00',
                'lat' => 12.3714,
                'lng' => -1.5197,
                'is_on_duty' => true,
            ],
        ];

        foreach ($pharmaciesData as $data) {
            $pharmacienId = User::where('type', UserType::PHARMACIEN->value)
                ->inRandomOrder()
                ->first()?->id;

            $pharmacy = Pharmacy::create(array_merge($data, [
                'pharmacien_id' => $pharmacienId,
            ]));

            $this->createWeekSchedule($pharmacy->id);
        }
    }

    private function createWeekSchedule(int $pharmacyId)
    {
        $days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

        foreach ($days as $day) {
            OpeningHours::create([
                'pharmacy_id' => $pharmacyId,
                'day' => $day,
                'opening_time' => '08:00:00',
                'closing_time' => $day === 'Saturday' ? '12:00:00' : '  20:00:00',
            ]);
        }
    }
}
