<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Pharmacy;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    protected function data(): array
    {
        return [
            [
                'productImage' => 'produits/dents_blanches.jpg',
                'productName' => '2 EN 1 EN DENTS BLANCHES',
                'description' => '',
                'price' => '2700',
                'stock' => 0,
                'expiredDate' => '2025-10-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/minc_caloriattack.jpg',
                'productName' => '4321 MINC CALORIATTACK SACH/14',
                'description' => '',
                'price' => '20450',
                'stock' => 0,
                'expiredDate' => '2026-05-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/slips_lavables.jpg',
                'productName' => '5 SLIPS LAVABLES ET EXTENS',
                'description' => '',
                'price' => '6600',
                'stock' => 0,
                'expiredDate' => '2027-01-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/vit_inj_amp.jpg',
                'productName' => '9 VIT INJ AMP 10ML BT/1',
                'description' => '',
                'price' => '2505',
                'stock' => 0,
                'expiredDate' => '2025-11-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/cerumen_unidose.jpg',
                'productName' => 'A CERUMEN UNIDOSE BT/10',
                'description' => '',
                'price' => '4000',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/a_derma_gel_lait.jpg',
                'productName' => 'A DERMA GEL MOUS LAIT AVOIN 500',
                'description' => '',
                'price' => '9722',
                'stock' => 0,
                'expiredDate' => '2025-12-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/a_derma_gel_surgra.jpg',
                'productName' => 'A DERMA GEL MOUSS SURGRA 250 ML',
                'description' => '',
                'price' => '7746',
                'stock' => 0,
                'expiredDate' => '2026-09-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/a_derma_pain_dermat.jpg',
                'productName' => 'A DERMA PAIN DERMAT AVOINE 100G',
                'description' => '',
                'price' => '2950',
                'stock' => 0,
                'expiredDate' => '2025-11-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/a_derma_pain_salicylique.jpg',
                'productName' => 'A DERMA PAIN SALICYLIQUE 100G',
                'description' => '',
                'price' => '4300',
                'stock' => 0,
                'expiredDate' => '2027-02-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/a_derma_pain_surgras.jpg',
                'productName' => 'A DERMA PAIN SURGRAS P/SECHE 100G',
                'description' => '',
                'price' => '6300',
                'stock' => 0,
                'expiredDate' => '2026-06-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abaisse_langue_bt1.jpg',
                'productName' => 'ABAISSE LANGUE BT/1',
                'description' => '',
                'price' => '10',
                'stock' => 0,
                'expiredDate' => '2027-07-07',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abaisse_langue_boite100.jpg',
                'productName' => 'ABAISSE LANGUE EN BOIS BT/100',
                'description' => '',
                'price' => '1050',
                'stock' => 0,
                'expiredDate' => '2026-03-25',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abaisse_langue_enf_boite250.jpg',
                'productName' => 'ABAISSE LANGUE ENF BOIS BT/250',
                'description' => '',
                'price' => '2160',
                'stock' => 0,
                'expiredDate' => '2025-09-17',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abaisse_langue_sterile_medline.jpg',
                'productName' => 'ABAISSE LANGUE STERILE MEDLINE/100',
                'description' => '',
                'price' => '1000',
                'stock' => 0,
                'expiredDate' => '2026-11-11',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abasaglar_kwikpen.jpg',
                'productName' => 'ABASAGLAR KWIKPEN 100UI/ML B/5 STYLOS',
                'description' => '',
                'price' => '50476',
                'stock' => 0,
                'expiredDate' => '2025-08-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abco.jpg',
                'productName' => 'ABCO',
                'description' => '',
                'price' => '8600',
                'stock' => 0,
                'expiredDate' => '2027-04-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abz_200mg_susp.jpg',
                'productName' => 'ABZ 200MG/5ML SUSP FL/10ML',
                'description' => '',
                'price' => '790',
                'stock' => 0,
                'expiredDate' => '2025-10-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abz_400mg_cpr_bt1.jpg',
                'productName' => 'ABZ 400MG CPR BT/1',
                'description' => '',
                'price' => '835',
                'stock' => 0,
                'expiredDate' => '2026-07-27',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/abz_400mg_cpr_bt3.jpg',
                'productName' => 'ABZ 400MG CPR BT/3',
                'description' => '',
                'price' => '2114',
                'stock' => 0,
                'expiredDate' => '2027-03-13',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acarilbial_sol_ext.jpg',
                'productName' => 'ACARILBIAL SOL EXT FL/200ML',
                'description' => '',
                'price' => '2580',
                'stock' => 0,
                'expiredDate' => '2026-02-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accroche_canne.jpg',
                'productName' => 'ACCROCHE CANNE MARRON AVEC AIMANT',
                'description' => '',
                'price' => '6200',
                'stock' => 0,
                'expiredDate' => '2027-05-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_activ_bandelet_25.jpg',
                'productName' => 'ACCU CHEK ACTIV BANDELET BT/25',
                'description' => '',
                'price' => '7675',
                'stock' => 0,
                'expiredDate' => '2026-07-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_activ_bandelet_50.jpg',
                'productName' => 'ACCU CHEK ACTIV BANDELET BT/50',
                'description' => '',
                'price' => '13882',
                'stock' => 0,
                'expiredDate' => '2027-01-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_activ_lect_kit.jpg',
                'productName' => 'ACCU CHEK ACTIV LECT KIT MG/DL',
                'description' => '',
                'price' => '17000',
                'stock' => 0,
                'expiredDate' => '2025-11-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_fastclix_autopiqueur.jpg',
                'productName' => 'ACCU CHEK FASTCLIX AUTOPIQUEUR',
                'description' => '',
                'price' => '14650',
                'stock' => 0,
                'expiredDate' => '2026-03-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_go_band_react_100.jpg',
                'productName' => 'ACCU CHEK GO BAND REACT BT/100',
                'description' => '',
                'price' => '59250',
                'stock' => 0,
                'expiredDate' => '2027-06-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_mobile_cassette_2x50.jpg',
                'productName' => 'ACCU CHEK MOBILE CASSETTE BT/2X50',
                'description' => '',
                'price' => '44450',
                'stock' => 0,
                'expiredDate' => '2026-09-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_multicl_lancet_200.jpg',
                'productName' => 'ACCU CHEK MULTICL LANCET/200 4',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2027-12-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_performa_band_2x50.jpg',
                'productName' => 'ACCU CHEK PERFORMA BAND BT/2X50',
                'description' => '',
                'price' => '44750',
                'stock' => 0,
                'expiredDate' => '2026-11-22',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_performa_50.jpg',
                'productName' => 'ACCU CHEK PERFORMA BT/50',
                'description' => '',
                'price' => '22375',
                'stock' => 0,
                'expiredDate' => '2025-10-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accu_chek_autopic_softclix.jpg',
                'productName' => 'ACCUCHEK AUTOPIC SOFTCLIX',
                'description' => '',
                'price' => '14500',
                'stock' => 0,
                'expiredDate' => '2026-08-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/accuzon_1g_sol_inj_1.jpg',
                'productName' => 'ACCUZON 1G SOL INJ BT/1',
                'description' => '',
                'price' => '3830',
                'stock' => 0,
                'expiredDate' => '2025-12-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aceclofair_100mg_cpr_10.jpg',
                'productName' => 'ACECLOFAIR 100MG CPR BT/10',
                'description' => '',
                'price' => '2480',
                'stock' => 0,
                'expiredDate' => '2026-04-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aceflamex_100mg_cpr_20.jpg',
                'productName' => 'ACEFLAMEX 100MG CPR BT/20',
                'description' => '',
                'price' => '2780',
                'stock' => 0,
                'expiredDate' => '2027-02-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acelodon_100mg_cpr_10.jpg',
                'productName' => 'ACELODON 100MG CPR BT/10',
                'description' => '',
                'price' => '1795',
                'stock' => 0,
                'expiredDate' => '2026-06-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acenland_cpb_10.jpg',
                'productName' => 'ACENLAND CPB/10',
                'description' => '',
                'price' => '1580',
                'stock' => 0,
                'expiredDate' => '2025-11-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acenland_p_100_500mg_cpr_10.jpg',
                'productName' => 'ACENLAND-P 100/500MG CPR BT/10',
                'description' => '',
                'price' => '1583',
                'stock' => 0,
                'expiredDate' => '2027-05-22',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acetafen_500mg_cpr_20.jpg',
                'productName' => 'ACETAFEN 500MG CPR BT/20',
                'description' => '',
                'price' => '600',
                'stock' => 0,
                'expiredDate' => '2026-03-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acfamol_40mg_im_iv_pdr_inj_f_solv_1.jpg',
                'productName' => 'ACFAMOL 40MG IM/IV PDR INJ F SOLV/1',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2027-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acfol_5mg_cpr_25.jpg',
                'productName' => 'ACFOL 5MG CPR BT/25',
                'description' => '',
                'price' => '2055',
                'stock' => 0,
                'expiredDate' => '2025-09-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acfran_cpr_30.jpg',
                'productName' => 'ACFRAN CPR BT/30',
                'description' => '',
                'price' => '3060',
                'stock' => 0,
                'expiredDate' => '2026-12-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acfran_sirop_200ml.jpg',
                'productName' => 'ACFRAN SIROP FL/200ML',
                'description' => '',
                'price' => '2780',
                'stock' => 0,
                'expiredDate' => '2027-01-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_200mg_cpr_10x100.jpg',
                'productName' => 'ACICLOVIR 200MG CPR 10X100',
                'description' => '',
                'price' => '24948',
                'stock' => 0,
                'expiredDate' => '2027-04-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_crt_5_creme_2g.jpg',
                'productName' => 'ACICLOVIR CRT 5% CREME 2G',
                'description' => '',
                'price' => '4600',
                'stock' => 0,
                'expiredDate' => '2026-11-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_mylan_250mg_10ml_bt_5.jpg',
                'productName' => 'ACICLOVIR MYLAN 250MG/10ML BT/5',
                'description' => '',
                'price' => '15645',
                'stock' => 0,
                'expiredDate' => '2027-01-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_mylan_250mg_10ml_vrac_1amp.jpg',
                'productName' => 'ACICLOVIR MYLAN 250MG/10ML VRAC/1AMP',
                'description' => '',
                'price' => '3130',
                'stock' => 0,
                'expiredDate' => '2026-07-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_mylan_500mg_20ml_bt_5.jpg',
                'productName' => 'ACICLOVIR MYLAN 500MG/20ML BT/5',
                'description' => '',
                'price' => '20100',
                'stock' => 0,
                'expiredDate' => '2027-09-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aciclovir_mylan_500mg_20ml_vrac_1amp.jpg',
                'productName' => 'ACICLOVIR MYLAN 500MG/20ML VRAC/1AMP',
                'description' => '',
                'price' => '4020',
                'stock' => 0,
                'expiredDate' => '2027-05-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_acetyl_salicylique_500mg_bt_1000.jpg',
                'productName' => 'ACIDE ACETYL SALICYLIQUE 500MG BT/1000',
                'description' => '',
                'price' => '4350',
                'stock' => 0,
                'expiredDate' => '2027-03-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_acetyl_salicylique_500mg_cpr_bl_20.jpg',
                'productName' => 'ACIDE ACETYL SALICYLIQUE 500MG CPR BL/20',
                'description' => '',
                'price' => '200',
                'stock' => 0,
                'expiredDate' => '2026-12-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_acetyl_ubi_cpr_500mg_bl_20.jpg',
                'productName' => 'ACIDE ACETYL UBI CPR 500MG BL/20',
                'description' => '',
                'price' => '200',
                'stock' => 0,
                'expiredDate' => '2026-11-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_acetyl_ubi_cpr_500mg_bt_1000.jpg',
                'productName' => 'ACIDE ACETYL UBI CPR 500MG BT/1000',
                'description' => '',
                'price' => '9585',
                'stock' => 0,
                'expiredDate' => '2027-06-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_benzoique_30g.jpg',
                'productName' => 'ACIDE BENZOIQUE 30G (whitfied\'s)',
                'description' => '',
                'price' => '525',
                'stock' => 0,
                'expiredDate' => '2026-10-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_borique_poudre_cpf_kg.jpg',
                'productName' => 'ACIDE BORIQUE POUDRE CPF KG',
                'description' => '',
                'price' => '20205',
                'stock' => 0,
                'expiredDate' => '2027-08-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_borique_pulv_sachet_30g_bt_20.jpg',
                'productName' => 'ACIDE BORIQUE PULV SACHET 30G BT/20',
                'description' => '',
                'price' => '11332',
                'stock' => 0,
                'expiredDate' => '2027-07-11',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_folique_5mg_cpr_bt_1000.jpg',
                'productName' => 'ACIDE FOLIQUE 5MG CPR BT/1000',
                'description' => '',
                'price' => '2840',
                'stock' => 0,
                'expiredDate' => '2027-02-25',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_folique_5mg_creat_bl_20.jpg',
                'productName' => 'ACIDE FOLIQUE 5MG CREAT BL/20',
                'description' => '',
                'price' => '615',
                'stock' => 0,
                'expiredDate' => '2026-09-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_folique_5mg_tm_cpr_bt_40.jpg',
                'productName' => 'ACIDE FOLIQUE 5MG TM CPR BT/40',
                'description' => '',
                'price' => '450',
                'stock' => 0,
                'expiredDate' => '2027-01-14',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_folique_5mg_vrac_20.jpg',
                'productName' => 'ACIDE FOLIQUE 5MG VRAC/20',
                'description' => '',
                'price' => '60',
                'stock' => 0,
                'expiredDate' => '2026-11-07',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicyliq_crist_cpf_250g.jpg',
                'productName' => 'ACIDE SALICYLIQ, CRIST, CPF 250G',
                'description' => '',
                'price' => '18580',
                'stock' => 0,
                'expiredDate' => '2027-03-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_1kg.jpg',
                'productName' => 'ACIDE SALICYLIQUE 1KG',
                'description' => '',
                'price' => '23760',
                'stock' => 0,
                'expiredDate' => '2027-06-22',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_cooper_5kg.jpg',
                'productName' => 'ACIDE SALICYLIQUE COOPER 5KG',
                'description' => '',
                'price' => '180310',
                'stock' => 0,
                'expiredDate' => '2028-01-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_cpf_100sach_1g_bt100.jpg',
                'productName' => 'ACIDE SALICYLIQUE CPF 100SACH/1G BT100',
                'description' => '',
                'price' => '25550',
                'stock' => 0,
                'expiredDate' => '2027-07-19',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_pdre_1g.jpg',
                'productName' => 'ACIDE SALICYLIQUE PDRE 1G',
                'description' => '',
                'price' => '100',
                'stock' => 0,
                'expiredDate' => '2026-10-29',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_pdre_1kg.jpg',
                'productName' => 'ACIDE SALICYLIQUE PDRE 1KG',
                'description' => '',
                'price' => '35150',
                'stock' => 0,
                'expiredDate' => '2028-02-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_pdre_250g.jpg',
                'productName' => 'ACIDE SALICYLIQUE PDRE 250G',
                'description' => '',
                'price' => '23244',
                'stock' => 0,
                'expiredDate' => '2027-09-29',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_pdre_500g.jpg',
                'productName' => 'ACIDE SALICYLIQUE PDRE 500G',
                'description' => '',
                'price' => '26400',
                'stock' => 0,
                'expiredDate' => '2027-11-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_salicylique_poudre_100g.jpg',
                'productName' => 'ACIDE SALICYLIQUE POUDRE /100G',
                'description' => '',
                'price' => '6600',
                'stock' => 0,
                'expiredDate' => '2027-08-03',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_tranexamique_agt_100mg_10.jpg',
                'productName' => 'ACIDE TRANEXAMIQUE AGT 100MG/10',
                'description' => '',
                'price' => '16687',
                'stock' => 0,
                'expiredDate' => '2027-05-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acide_tranexamique_agt_100mg_1amp.jpg',
                'productName' => 'ACIDE TRANEXAMIQUE AGT 100MG/1AMP',
                'description' => '',
                'price' => '1669',
                'stock' => 0,
                'expiredDate' => '2026-10-22',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_100mg_12_5mg_fl_60ml.jpg',
                'productName' => 'ACLAV 100MG/12,5MG FL/60ML',
                'description' => '',
                'price' => '5005',
                'stock' => 0,
                'expiredDate' => '2027-08-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_100mg_12_5mg_pdre_susp_fl_30ml.jpg',
                'productName' => 'ACLAV 100MG/12,5MG PDRE SUSP FL/30ML',
                'description' => '',
                'price' => '2505',
                'stock' => 0,
                'expiredDate' => '2026-11-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_1g_125mg_sach_bt_16.jpg',
                'productName' => 'ACLAV 1G/125MG SACH BT/16',
                'description' => '',
                'price' => '8270',
                'stock' => 0,
                'expiredDate' => '2027-04-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_1g_125mg_sachet_bt_12.jpg',
                'productName' => 'ACLAV 1G/125MG SACHET BT/12',
                'description' => '',
                'price' => '5600',
                'stock' => 0,
                'expiredDate' => '2026-12-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_1g_200mg_prde_sol_inj_f_1.jpg',
                'productName' => 'ACLAV 1G/200MG PRDE SOL INJ F/1',
                'description' => '',
                'price' => '3195',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_500_62_5mg_ge_sach_bt_12.jpg',
                'productName' => 'ACLAV 500/62,5MG GE SACH BT/12',
                'description' => '',
                'price' => '5560',
                'stock' => 0,
                'expiredDate' => '2027-06-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_500mg_50mg_pdre_sol_inj_f_1.jpg',
                'productName' => 'ACLAV 500MG/50MG PDRE SOL INJ F/1',
                'description' => '',
                'price' => '1945',
                'stock' => 0,
                'expiredDate' => '2026-11-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclav_500mg_62_5mg_sachet_bt_16.jpg',
                'productName' => 'ACLAV 500MG/62,5MG SACHET BT/16',
                'description' => '',
                'price' => '6820',
                'stock' => 0,
                'expiredDate' => '2027-02-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclin_gel_tb_15g.jpg',
                'productName' => 'ACLIN GEL TB/15G',
                'description' => '',
                'price' => '4030',
                'stock' => 0,
                'expiredDate' => '2027-03-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclogel_1_5_gel_t_30g.jpg',
                'productName' => 'ACLOGEL 1,5% GEL T/30G',
                'description' => '',
                'price' => '1485',
                'stock' => 0,
                'expiredDate' => '2026-12-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/aclop_100mg_500mg_cpr_bt_10.jpg',
                'productName' => 'ACLOP 100MG/500MG CPR BT/10',
                'description' => '',
                'price' => '2225',
                'stock' => 0,
                'expiredDate' => '2026-10-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acnet_huile_medicale_100ml.jpg',
                'productName' => 'ACNET HUILE MEDICALE 100ML',
                'description' => '',
                'price' => '3100',
                'stock' => 0,
                'expiredDate' => '2027-07-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acnet_lotion_florale_125ml.jpg',
                'productName' => 'ACNET LOTION FLORALE 125ML',
                'description' => '',
                'price' => '2418',
                'stock' => 0,
                'expiredDate' => '2026-09-18',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acnet_lotion_medicale_fl_125ml.jpg',
                'productName' => 'ACNET LOTION MEDICALE FL/125ML',
                'description' => '',
                'price' => '3875',
                'stock' => 0,
                'expiredDate' => '2027-01-22',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acnetrait_arrow_10mg_caps_bt_30.jpg',
                'productName' => 'ACNETRAIT ARROW 10MG CAPS BT/30',
                'description' => '',
                'price' => '12600',
                'stock' => 0,
                'expiredDate' => '2027-05-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acnetrait_arrow_40mg_caps_bt_30.jpg',
                'productName' => 'ACNETRAIT ARROW 40MG CAPS BT/30',
                'description' => '',
                'price' => '41910',
                'stock' => 0,
                'expiredDate' => '2027-09-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acofan_100mg_cpr_bt_30.jpg',
                'productName' => 'ACOFAN 100MG CPR BT/30',
                'description' => '',
                'price' => '3890',
                'stock' => 0,
                'expiredDate' => '2027-04-02',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actapulgite_pediatrique_bt_20.jpg',
                'productName' => 'ACTAPULGITE PEDIATRIQUE BT/20',
                'description' => '',
                'price' => '1660',
                'stock' => 0,
                'expiredDate' => '2026-11-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actapulgite_sach_bt_30.jpg',
                'productName' => 'ACTAPULGITE SACH BT/30',
                'description' => '',
                'price' => '3705',
                'stock' => 0,
                'expiredDate' => '2027-01-10',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acti_5_amp_buv_5ml_bt_30.jpg',
                'productName' => 'ACTI 5 AMP BUV 5ML BT/30',
                'description' => '',
                'price' => '4065',
                'stock' => 0,
                'expiredDate' => '2026-12-20',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acticarbine_cpr_drag_bt_42.jpg',
                'productName' => 'ACTICARBINE CPR DRAG BT/42',
                'description' => '',
                'price' => '1875',
                'stock' => 0,
                'expiredDate' => '2027-03-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actifed_jour_et_nuit_cpr_bt_16.jpg',
                'productName' => 'ACTIFED JOUR ET NUIT CPR BT/16',
                'description' => '',
                'price' => '8455',
                'stock' => 0,
                'expiredDate' => '2027-06-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimag_sirop_fl_100ml.jpg',
                'productName' => 'ACTIMAG SIROP FL/100ML',
                'description' => '',
                'price' => '4005',
                'stock' => 0,
                'expiredDate' => '2026-10-12',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_claviculla_sangle_s_65_90cm.jpg',
                'productName' => 'ACTIMOVE CLAVICULA SANGLE S/65-90CM',
                'description' => '',
                'price' => '6600',
                'stock' => 0,
                'expiredDate' => '2027-05-02',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_gauntlet_att_p_p_drt_l.jpg',
                'productName' => 'ACTIMOVE GAUNTLET ATT P/P DRT L',
                'description' => '',
                'price' => '9650',
                'stock' => 0,
                'expiredDate' => '2027-04-11',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_genu_eco_clips_att_40cm_u_1.jpg',
                'productName' => 'ACTIMOVE GENU ECO CLIPS ATT 40CM U/1',
                'description' => '',
                'price' => '20100',
                'stock' => 0,
                'expiredDate' => '2027-08-09',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_genuvital_3d_genou_ouvert_tl.jpg',
                'productName' => 'ACTIMOVE GENUVITAL 3D GENOU OUVERT TL',
                'description' => '',
                'price' => '29750',
                'stock' => 0,
                'expiredDate' => '2027-07-23',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_genuvital_3d_ouvert_ts.jpg',
                'productName' => 'ACTIMOVE GENUVITAL 3D OUVERT TS',
                'description' => '',
                'price' => '36100',
                'stock' => 0,
                'expiredDate' => '2027-06-17',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_lombacare_ceint_noir_xl.jpg',
                'productName' => 'ACTIMOVE LOMBACARE CEINT NOIR XL',
                'description' => '',
                'price' => '55750',
                'stock' => 0,
                'expiredDate' => '2027-09-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_lombacare_mot_ceint_noir_txxl.jpg',
                'productName' => 'ACTIMOVE LOMBACARE MOT CEINT NOIR TXXL',
                'description' => '',
                'price' => '47875',
                'stock' => 0,
                'expiredDate' => '2027-11-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_lombacare_motion_ceint_noir_tl.jpg',
                'productName' => 'ACTIMOVE LOMBACARE MOTION CEINT NOIR TL',
                'description' => '',
                'price' => '50980',
                'stock' => 0,
                'expiredDate' => '2027-10-05',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_lombacare_motion_ceint_noir_tm.jpg',
                'productName' => 'ACTIMOVE LOMBACARE MOTION CEINT NOIR TM',
                'description' => '',
                'price' => '55470',
                'stock' => 0,
                'expiredDate' => '2027-12-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_conf_echarp_l.jpg',
                'productName' => 'ACTIMOVE UMERUS CONF ECHARP L',
                'description' => '',
                'price' => '6890',
                'stock' => 0,
                'expiredDate' => '2027-01-25',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_conf_echarp_m.jpg',
                'productName' => 'ACTIMOVE UMERUS CONF ECHARP M',
                'description' => '',
                'price' => '6935',
                'stock' => 0,
                'expiredDate' => '2026-11-19',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_conf_echarp_xl.jpg',
                'productName' => 'ACTIMOVE UMERUS CONF ECHARP XL',
                'description' => '',
                'price' => '6825',
                'stock' => 0,
                'expiredDate' => '2027-04-27',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_eco_ece_l.jpg',
                'productName' => 'ACTIMOVE UMERUS ECO ECE L',
                'description' => '',
                'price' => '9975',
                'stock' => 0,
                'expiredDate' => '2027-03-13',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_eco_ece_m.jpg',
                'productName' => 'ACTIMOVE UMERUS ECO ECE M',
                'description' => '',
                'price' => '9750',
                'stock' => 0,
                'expiredDate' => '2027-07-21',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_eco_ece_s.jpg',
                'productName' => 'ACTIMOVE UMERUS ECO ECE S',
                'description' => '',
                'price' => '9890',
                'stock' => 0,
                'expiredDate' => '2026-12-29',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actimove_umerus_eco_ece_xl.jpg',
                'productName' => 'ACTIMOVE UMERUS ECO ECE XL',
                'description' => '',
                'price' => '10000',
                'stock' => 0,
                'expiredDate' => '2027-09-09',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actinac_100mg_10.jpg',
                'productName' => 'ACTINAC 100MG CPR BT/10',
                'description' => '',
                'price' => '2570',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actinac_100mg_30.jpg',
                'productName' => 'ACTINAC 100MG CPR BT/30',
                'description' => '',
                'price' => '7645',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actinac_plus_100_500.jpg',
                'productName' => 'ACTINAC PLUS 100MG/500MG CPR B/10',
                'description' => '',
                'price' => '2990',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actipoche_cervicales.jpg',
                'productName' => 'ACTIPOCHE CERVICALES TRAPEZES',
                'description' => '',
                'price' => '8775',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actipoche_chfroid_mm.jpg',
                'productName' => 'ACTIPOCHE CHAUD/FROID MM11X27',
                'description' => '',
                'price' => '3870',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actipoche_chfroid_pm.jpg',
                'productName' => 'ACTIPOCHE CHAUD/FROID PM 10X15',
                'description' => '',
                'price' => '2575',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actipoche_genou.jpg',
                'productName' => 'ACTIPOCHE GENOU',
                'description' => '',
                'price' => '6315',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actipoche_20x30.jpg',
                'productName' => 'ACTIPOCHE POC CH/FROID 20X30CM',
                'description' => '',
                'price' => '8455',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actiskenan_20mg.jpg',
                'productName' => 'ACTISKENAN 20MG GELULE BT/14',
                'description' => '',
                'price' => '6285',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/activox_mielcitron.jpg',
                'productName' => 'ACTIVOX PAST S SUC MIEL CITRON BT/24',
                'description' => '',
                'price' => '7925',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actopenum_500mg.jpg',
                'productName' => 'ACTOPENUM 500MG IM/IV PDR INJ F/1 SOLV1',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actovzn_kit.jpg',
                'productName' => 'ACTOVZN KIT CPR BT/4',
                'description' => '',
                'price' => '4160',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actrapid_hm_40.jpg',
                'productName' => 'ACTRAPID HM 40 NOVO INSULINE IMMeD BT/1',
                'description' => '',
                'price' => '4725',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/actrapid_penfill_5x3ml.jpg',
                'productName' => 'ACTRAPID PENFILL BT/5 3ML',
                'description' => '',
                'price' => '34210',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acudrox_susp_250.jpg',
                'productName' => 'ACUDROX SUSP 250MG/5ML 30ML',
                'description' => '',
                'price' => '3335',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acuilix_20mg.jpg',
                'productName' => 'ACUILIX 20MG CPR SEC BT/28',
                'description' => '',
                'price' => '6495',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acumol_100_500.jpg',
                'productName' => 'ACUMOL 100MG/500MG CPR BT/20',
                'description' => '',
                'price' => '4170',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acupan_inj_vrac.jpg',
                'productName' => 'ACUPAN INJ 1AMP VRAC',
                'description' => '',
                'price' => '756',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acupan_inj_5.jpg',
                'productName' => 'ACUPAN INJ 2ML BT/5',
                'description' => '',
                'price' => '3780',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acyclovir_denk_200.jpg',
                'productName' => 'ACYCLOVIR DENK 200MG CPR BT/25',
                'description' => '',
                'price' => '9120',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/acyclovir_denk_creme_5pct.jpg',
                'productName' => 'ACYCLOVIR DENK CREME 5% T/7G',
                'description' => '',
                'price' => '3755',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adalate_10mg_caps_30.jpg',
                'productName' => 'ADALATE 10MG CAPS BT/30',
                'description' => '',
                'price' => '3670',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adaptateur_porte_tube.jpg',
                'productName' => 'ADAPTATEUR PORTE-TUBE petit tub(retract)',
                'description' => '',
                'price' => '300',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adenuric_120mg_pel_28.jpg',
                'productName' => 'ADENURIC 120MG CPR PEL BT/28',
                'description' => '',
                'price' => '20180',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adenuric_80mg_pell_28.jpg',
                'productName' => 'ADENURIC 80MG CPR PELL BT/28',
                'description' => '',
                'price' => '25905',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adepal_plaq_1_21.jpg',
                'productName' => 'ADEPAL PLAQ/1 CPR BT/21',
                'description' => '',
                'price' => '2405',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adepal_plaq_3_3x21.jpg',
                'productName' => 'ADEPAL PLAQ/3 CPR BT/3X21',
                'description' => '',
                'price' => '5677',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adione_10mg_10mg_10.jpg',
                'productName' => 'ADIONE 10MG/10MG CPR BT/10',
                'description' => '',
                'price' => '2624',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adione_10mg_10mg_30.jpg',
                'productName' => 'ADIONE 10MG/10MG CPR BT/30',
                'description' => '',
                'price' => '6320',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adrenaline_1mg_1ml_10.jpg',
                'productName' => 'ADRENALINE 1MG/1ML BT/10 AGUETTANT',
                'description' => '',
                'price' => '11660',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adrenaline_1mg_ml_vrac_1.jpg',
                'productName' => 'ADRENALINE 1MG/ML VRAC/1 AGUETTANT',
                'description' => '',
                'price' => '1166',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/adrenaline_1mg_mlinj.jpg',
                'productName' => 'ADRENALINE 1MG/MLINJ',
                'description' => '',
                'price' => '500',
                'stock' => 0,
                'expiredDate' => '2026-08-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ADRIDE 2MG CPR SEC BT/30',
                'description' => '',
                'price' => '2500',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ADRIDE 4MG CPR SEC BT/30',
                'description' => '',
                'price' => '6820',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ADVILMED 400MG CPR BT/20',
                'description' => '',
                'price' => '2100',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ADVILMED SUSP BUV 20MG/ML FL/200ML',
                'description' => '',
                'price' => '4830',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AERIUS 5MG CPR BT/15',
                'description' => '',
                'price' => '6215',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AERIUS 5MG CPR PELL BT/7',
                'description' => '',
                'price' => '3125',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AERIUS SIROP FL/60ML CUIL 5ML',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AEROCHAMBRE CHAMBR INHAL ENF',
                'description' => '',
                'price' => '34200',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AEROL 100MCG AEROSOL 200 DOSES',
                'description' => '',
                'price' => '2345',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AEROSOL PNEUMA PARI BOY SX(2002517)',
                'description' => '',
                'price' => '434070',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AFCOVIT FER SIROP FL/200ML',
                'description' => '',
                'price' => '2780',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AFINE 500MG CPR BL/4',
                'description' => '',
                'price' => '300',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AFINE 500MG CPR BT/20X4',
                'description' => '',
                'price' => '5940',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AFSC 1G/150MG KIT COMP BT/4',
                'description' => '',
                'price' => '4310',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AFTAGEL GEL BUC T/15ML',
                'description' => '',
                'price' => '2945',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AGRAFEUSE CHIRUGICALE CUTANNEE SM',
                'description' => '',
                'price' => '9250',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AGYRAX CPR BT/15',
                'description' => '',
                'price' => '2155',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG BD MICROF  12,7MM PEN BT/100',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG BD MICROF  4MM PEN BT/100',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG BD MICROF  5MM PEN BT/100',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2026-01-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG BD MICROF 8MM PEN BT100',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG HUB SURECAN CO 22G 25MM',
                'description' => '',
                'price' => '2375',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG HUB SURECAN DR 22G 30MM',
                'description' => '',
                'price' => '2375',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG NOVOFINE 8MM 30G BT/100',
                'description' => '',
                'price' => '16100',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG NOVOTWIST A 8MM 30G BT/100',
                'description' => '',
                'price' => '17100',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG STYL INS MARQUE VERT 8MM 31G BT/100',
                'description' => '',
                'price' => '17825',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG STYLO DUO BD SECU 30G 5MM',
                'description' => '',
                'price' => '950',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG STYLO DUO BD SECU 30G 8MM',
                'description' => '',
                'price' => '950',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG VACUTAINER ECLIP 21G',
                'description' => '',
                'price' => '895',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG VACUTAINER ECLIP 22G',
                'description' => '',
                'price' => '665',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIG VACUTAINER ECLIP 22G SCH',
                'description' => '',
                'price' => '895',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL HUBER COURBE 25X7',
                'description' => '',
                'price' => '1900',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PONCT LOMB G18 ROSE',
                'description' => '',
                'price' => '965',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PONCT LOMB G20 JAUNE',
                'description' => '',
                'price' => '965',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PONCT LOMB G22 NOIR',
                'description' => '',
                'price' => '2000',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PONCT LOMB G25 INTRO',
                'description' => '',
                'price' => '0',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PONCT LOMB G25X120MM AVEC INTROD',
                'description' => '',
                'price' => '6400',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL POUR PRELEVEMENT SANGUIN',
                'description' => '',
                'price' => '75',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PR NEUROSTIMULATION G20 150MM',
                'description' => '',
                'price' => '10695',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PR NEUROSTIMULATION G20 50MM',
                'description' => '',
                'price' => '10300',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PR NEUROSTIMULATION G21 100MM',
                'description' => '',
                'price' => '10200',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PR NEUROSTIMULATION G22 50MM',
                'description' => '',
                'price' => '14875',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL PR NEUROSTIMULATION G22 80MM',
                'description' => '',
                'price' => '14900',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL SPINALE BD PED 25G1 25MM',
                'description' => '',
                'price' => '5650',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL SPINALE BD PED 25G2 50MM',
                'description' => '',
                'price' => '5650',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL SPINALE BD PED G26 88MM',
                'description' => '',
                'price' => '5650',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILL SPINALE G25 (0,5x90mm',
                'description' => '',
                'price' => '1855',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILLE A PL SS INTRODUC 18GX90',
                'description' => '',
                'price' => '800',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILLE A PL SS INTRODUC 20G/90MM',
                'description' => '',
                'price' => '800',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIGUILLE A PL SS INTRODUC 22X90MM',
                'description' => '',
                'price' => '800',
                'stock' => 0,
                'expiredDate' => '2026-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIL ELUSANES GELULE BT/20',
                'description' => '',
                'price' => '4900',
                'stock' => 0,
                'expiredDate' => '2025-09-30',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIMANT OCULAIRE AVEC LOUPE COMED',
                'description' => '',
                'price' => '18985',
                'stock' => 0,
                'expiredDate' => '2028-06-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIMANT OCULAIRE COMED',
                'description' => '',
                'price' => '17100',
                'stock' => 0,
                'expiredDate' => '2028-06-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIRTAL 100MG CPR BT/10',
                'description' => '',
                'price' => '3630',
                'stock' => 0,
                'expiredDate' => '2026-02-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AIRTAL 100MG CPR BT/40',
                'description' => '',
                'price' => '11410',
                'stock' => 0,
                'expiredDate' => '2026-02-28',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'AKARYD 10MG CPR BT/20',
                'description' => '',
                'price' => '5420',
                'stock' => 0,
                'expiredDate' => '2027-03-15',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALAIRGIX 10MG CPR BT/7',
                'description' => '',
                'price' => '3210',
                'stock' => 0,
                'expiredDate' => '2027-04-01',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA CREME MAIN ONGLE 50ML',
                'description' => '',
                'price' => '2600',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA CREME PIED SEC 125 ML',
                'description' => '',
                'price' => '5975',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA GEL JAM LOURD 125ML',
                'description' => '',
                'price' => '7200',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA SHAMP A-PELLICULAIRE 125ML',
                'description' => '',
                'price' => '4100',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA SHAMP CHEV GRAS 125ML',
                'description' => '',
                'price' => '3700',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA SHAMP CHEV SEC 125ML',
                'description' => '',
                'price' => '3700',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
            [
                'productImage' => 'produits/default.jpg',
                'productName' => 'ALASKA SHAMP USAGE FREQ 125ML',
                'description' => '',
                'price' => '3700',
                'stock' => 0,
                'expiredDate' => '2025-12-31',
                'laborator' => '',
            ],
        ];

    }

    public function run()
    {
        Product::truncate();

        foreach ($this->data() as $product) {
            Product::create(array_merge($product, [
                'pharmacy_id' => Pharmacy::inRandomOrder()->value('id'),
            ]));
        }
    }
}
